version: '3'
services:
  bookstore-db:
    image: mysql:8.0   
    volumes:
       - dbdata:/var/lib/mysql
       - ./DB_Init:/docker-entrypoint-initdb.d
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: bookstore
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  bookstore-api:
    depends_on:
      - bookstore-db    
    build: .    
    ports:
      - "3000:80"
    volumes:
      - logs:/app/logs
    environment:
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  dbdata:
  logs: